"""stage 3: citations, classifications, classification source checks

Revision ID: 4381d4019386
Revises: 5afe43f05819
Create Date: 2026-09-08 11:20:15.133135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4381d4019386'
down_revision: Union[str, None] = '5afe43f05819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_identifier', sa.Text(), nullable=False),
    sa.Column('from_title', sa.Text(), nullable=False),
    sa.Column('from_citation', sa.Text(), nullable=True),
    sa.Column('from_heading', sa.Text(), nullable=True),
    sa.Column('release_label', sa.Text(), nullable=False),
    sa.Column('release_seq', sa.Integer(), nullable=True),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('note_topic', sa.Text(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('to_identifier', sa.Text(), nullable=False),
    sa.Column('to_kind', sa.Text(), nullable=False),
    sa.Column('to_law', sa.Text(), nullable=True),
    sa.Column('to_path', sa.Text(), nullable=True),
    sa.Column('to_section_num', sa.Text(), nullable=True),
    sa.Column('to_congress', sa.Integer(), nullable=True),
    sa.Column('to_number', sa.Integer(), nullable=True),
    sa.Column('to_chapter', sa.Integer(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('to_volume', sa.Integer(), nullable=True),
    sa.Column('to_page', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_from_identifier'), 'citations', ['from_identifier'], unique=False)
    op.create_index(op.f('ix_citations_from_title'), 'citations', ['from_title'], unique=False)
    op.create_index(op.f('ix_citations_release_label'), 'citations', ['release_label'], unique=False)
    op.create_index(op.f('ix_citations_to_identifier'), 'citations', ['to_identifier'], unique=False)
    op.create_index('ix_citations_to_law_section', 'citations', ['to_law', 'to_section_num'], unique=False)
    op.create_index('ix_citations_to_stat', 'citations', ['to_volume', 'to_page'], unique=False)
    op.create_table('classification_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('congress', sa.Integer(), nullable=False),
    sa.Column('session', sa.Integer(), nullable=False),
    sa.Column('session_label', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_filename', sa.Text(), nullable=True),
    sa.Column('covered_laws_text', sa.Text(), nullable=True),
    sa.Column('covered_ranges', sa.JSON(), nullable=False),
    sa.Column('first_law', sa.Integer(), nullable=True),
    sa.Column('last_law', sa.Integer(), nullable=True),
    sa.Column('prepared_date', sa.Date(), nullable=True),
    sa.Column('stat_volume', sa.Integer(), nullable=True),
    sa.Column('upstream_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('mirrored_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('congress', 'session', 'kind', name='uq_classification_files')
    )
    op.create_table('classification_source_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('congress', sa.Integer(), nullable=True),
    sa.Column('files_seen', sa.Integer(), nullable=True),
    sa.Column('files_loaded', sa.Integer(), nullable=True),
    sa.Column('files_unchanged', sa.Integer(), nullable=True),
    sa.Column('rows_loaded', sa.Integer(), nullable=True),
    sa.Column('upstream_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('upstream_covered_text', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('congress', sa.Integer(), nullable=False),
    sa.Column('session', sa.Integer(), nullable=False),
    sa.Column('row_seq', sa.Integer(), nullable=False),
    sa.Column('raw_line', sa.Text(), nullable=True),
    sa.Column('title_raw', sa.Text(), nullable=True),
    sa.Column('title_num', sa.Text(), nullable=True),
    sa.Column('is_appendix', sa.Boolean(), nullable=False),
    sa.Column('section_raw', sa.Text(), nullable=True),
    sa.Column('section_norm', sa.Text(), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('is_note', sa.Boolean(), nullable=False),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('transfer_counterpart', sa.Text(), nullable=True),
    sa.Column('act_name', sa.Text(), nullable=True),
    sa.Column('usc_identifier', sa.Text(), nullable=True),
    sa.Column('pl_congress', sa.Integer(), nullable=True),
    sa.Column('pl_num', sa.Integer(), nullable=True),
    sa.Column('pl_label', sa.Text(), nullable=True),
    sa.Column('pl_section_raw', sa.Text(), nullable=False),
    sa.Column('pl_section_num', sa.Text(), nullable=True),
    sa.Column('new_section_quote', sa.Text(), nullable=True),
    sa.Column('stat_volume', sa.Integer(), nullable=True),
    sa.Column('stat_pages', sa.JSON(), nullable=False),
    sa.Column('stat_page_labels', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['classification_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'row_seq', name='uq_classifications_row')
    )
    op.create_index(op.f('ix_classifications_file_id'), 'classifications', ['file_id'], unique=False)
    op.create_index('ix_classifications_pl', 'classifications', ['pl_congress', 'pl_num', 'pl_section_num'], unique=False)
    op.create_index(op.f('ix_classifications_usc_identifier'), 'classifications', ['usc_identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classifications_usc_identifier'), table_name='classifications')
    op.drop_index('ix_classifications_pl', table_name='classifications')
    op.drop_index(op.f('ix_classifications_file_id'), table_name='classifications')
    op.drop_table('classifications')
    op.drop_table('classification_source_checks')
    op.drop_table('classification_files')
    op.drop_index('ix_citations_to_stat', table_name='citations')
    op.drop_index('ix_citations_to_law_section', table_name='citations')
    op.drop_index(op.f('ix_citations_to_identifier'), table_name='citations')
    op.drop_index(op.f('ix_citations_release_label'), table_name='citations')
    op.drop_index(op.f('ix_citations_from_title'), table_name='citations')
    op.drop_index(op.f('ix_citations_from_identifier'), table_name='citations')
    op.drop_table('citations')
    # ### end Alembic commands ###
