"""initial schema

Revision ID: 5afe43f05819
Revises: 
Create Date: 2026-09-07 19:46:57.844837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5afe43f05819'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laws',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('congress', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('chapter', sa.Integer(), nullable=True),
    sa.Column('enacted', sa.Date(), nullable=True),
    sa.Column('doc_type', sa.Text(), nullable=True),
    sa.Column('official_title', sa.Text(), nullable=True),
    sa.Column('short_titles', sa.JSON(), nullable=False),
    sa.Column('stat_volume', sa.Integer(), nullable=False),
    sa.Column('stat_page_first', sa.Text(), nullable=True),
    sa.Column('stat_page_last', sa.Text(), nullable=True),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.Column('source_collection', sa.Text(), nullable=False),
    sa.Column('source_package', sa.Text(), nullable=False),
    sa.Column('source_granule', sa.Text(), nullable=True),
    sa.Column('seq_in_volume', sa.Integer(), nullable=False),
    sa.Column('provenance_text', sa.Text(), nullable=False),
    sa.Column('provenance_identifiers', sa.Text(), nullable=False),
    sa.Column('xml', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_index('ix_laws_congress_number', 'laws', ['congress', 'number'], unique=False)
    op.create_index('ix_laws_volume_seq', 'laws', ['stat_volume', 'seq_in_volume'], unique=False)
    op.create_table('source_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection', sa.Text(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('newest_last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('newest_package', sa.Text(), nullable=True),
    sa.Column('packages_seen', sa.Integer(), nullable=True),
    sa.Column('new_packages', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_checks_collection'), 'source_checks', ['collection'], unique=False)
    op.create_table('comps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Text(), nullable=False),
    sa.Column('package_id', sa.Text(), nullable=False),
    sa.Column('identifier_prefix', sa.Text(), nullable=False),
    sa.Column('law_congress', sa.Integer(), nullable=True),
    sa.Column('law_number', sa.Integer(), nullable=True),
    sa.Column('law_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('display_title', sa.Text(), nullable=True),
    sa.Column('short_titles', sa.JSON(), nullable=False),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('partial_of', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['law_id'], ['laws.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id'),
    sa.UniqueConstraint('package_id')
    )
    op.create_index(op.f('ix_comps_identifier_prefix'), 'comps', ['identifier_prefix'], unique=False)
    op.create_index(op.f('ix_comps_law_id'), 'comps', ['law_id'], unique=False)
    op.create_table('law_aliases',
    sa.Column('identifier', sa.Text(), nullable=False),
    sa.Column('law_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['law_id'], ['laws.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('identifier')
    )
    op.create_index(op.f('ix_law_aliases_law_id'), 'law_aliases', ['law_id'], unique=False)
    op.create_table('stat_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('page', sa.Text(), nullable=False),
    sa.Column('law_id', sa.Integer(), nullable=False),
    sa.Column('starts_here', sa.Boolean(), nullable=False),
    sa.Column('unit_identifier', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['law_id'], ['laws.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('volume', 'page', 'law_id', name='uq_stat_pages')
    )
    op.create_index(op.f('ix_stat_pages_law_id'), 'stat_pages', ['law_id'], unique=False)
    op.create_index('ix_stat_pages_volume_page', 'stat_pages', ['volume', 'page'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('law_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.Text(), nullable=False),
    sa.Column('occurrence', sa.Integer(), nullable=False),
    sa.Column('parent_identifier', sa.Text(), nullable=True),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('num', sa.Text(), nullable=True),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('section_num', sa.Text(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('ancestors', sa.JSON(), nullable=False),
    sa.Column('xml', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('first_page', sa.Text(), nullable=True),
    sa.Column('pages', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['law_id'], ['laws.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier', 'occurrence', name='uq_units_identifier')
    )
    op.create_index(op.f('ix_units_law_id'), 'units', ['law_id'], unique=False)
    op.create_index('ix_units_law_section_num', 'units', ['law_id', 'section_num'], unique=False)
    op.create_table('comp_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comp_id', sa.Integer(), nullable=False),
    sa.Column('current_through_pl', sa.Text(), nullable=True),
    sa.Column('current_through_date', sa.Date(), nullable=True),
    sa.Column('govinfo_last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('xml', sa.Text(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['comp_id'], ['comps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comp_id', 'content_hash', name='uq_comp_versions_hash')
    )
    op.create_index(op.f('ix_comp_versions_comp_id'), 'comp_versions', ['comp_id'], unique=False)
    op.create_table('comp_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comp_version_id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.Text(), nullable=False),
    sa.Column('parent_identifier', sa.Text(), nullable=True),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('num', sa.Text(), nullable=True),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('section_num', sa.Text(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('ancestors', sa.JSON(), nullable=False),
    sa.Column('xml', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('usc_refs', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['comp_version_id'], ['comp_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comp_version_id', 'identifier', name='uq_comp_units_identifier')
    )
    op.create_index(op.f('ix_comp_units_comp_version_id'), 'comp_units', ['comp_version_id'], unique=False)
    op.create_index('ix_comp_units_identifier', 'comp_units', ['identifier'], unique=False)
    op.create_index('ix_comp_units_version_section', 'comp_units', ['comp_version_id', 'section_num'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comp_units_version_section', table_name='comp_units')
    op.drop_index('ix_comp_units_identifier', table_name='comp_units')
    op.drop_index(op.f('ix_comp_units_comp_version_id'), table_name='comp_units')
    op.drop_table('comp_units')
    op.drop_index(op.f('ix_comp_versions_comp_id'), table_name='comp_versions')
    op.drop_table('comp_versions')
    op.drop_index('ix_units_law_section_num', table_name='units')
    op.drop_index(op.f('ix_units_law_id'), table_name='units')
    op.drop_table('units')
    op.drop_index('ix_stat_pages_volume_page', table_name='stat_pages')
    op.drop_index(op.f('ix_stat_pages_law_id'), table_name='stat_pages')
    op.drop_table('stat_pages')
    op.drop_index(op.f('ix_law_aliases_law_id'), table_name='law_aliases')
    op.drop_table('law_aliases')
    op.drop_index(op.f('ix_comps_law_id'), table_name='comps')
    op.drop_index(op.f('ix_comps_identifier_prefix'), table_name='comps')
    op.drop_table('comps')
    op.drop_index(op.f('ix_source_checks_collection'), table_name='source_checks')
    op.drop_table('source_checks')
    op.drop_index('ix_laws_volume_seq', table_name='laws')
    op.drop_index('ix_laws_congress_number', table_name='laws')
    op.drop_table('laws')
    # ### end Alembic commands ###
